apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 1 # Set the desired number of replicas
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: pyhton-app
          image: yash5090/pyhton-monitoring:latest # Replace with your Docker image name
          ports:
            - containerPort: 5000 # Expose the port specified in your Dockerfile

---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: dotnet-app
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 5000 # Port in the container
  type: NodePort # Use NodePort service type            
